export default defineAppConfig({
  pages: [
    'pages/hub/index',
    'pages/index/index',
    'pages/product/index',
    'pages/redeem/index',
    'pages/cart/index',
    'pages/address/index',
    'pages/profile/index',
    'pages/login/index',
    'pages/register/index',
    'pages/admin/index',
    'pages/admin/products',
    'pages/admin/codes',
    'pages/admin/users',
    'pages/admin/orders',
    'pages/admin/invites',
    'pages/admin/claims',
    'pages/admin/content',
    'pages/admin/categories',
    'pages/admin/settings',
    'pages/admin/batch-points',
    'pages/admin/quarterly-award',
    'pages/admin/batch-history',
    'pages/admin/batch-adjust',
    'pages/admin/travel',
    'pages/admin/tags',
    'pages/admin/reservation-approvals',
    'pages/admin/email-products',
    'pages/admin/email-content',
    'pages/admin/reports',
    'pages/admin/credentials',
    'pages/orders/index',
    'pages/order-detail/index',
    'pages/order-confirm/index',
    'pages/forgot-password/index',
    'pages/reset-password/index',
    'pages/claims/index',
    'pages/travel-apply/index',
    'pages/my-travel/index',
    'pages/settings/index',
    'pages/content/index',
    'pages/content/detail',
    'pages/content/upload',
    'pages/content/mine',
    'pages/leaderboard/index',
    'pages/privacy/index',
    'pages/code-of-conduct/index',
  ],
  window: {
    backgroundTextStyle: 'dark',
    navigationBarBackgroundColor: '#0a0b0f',
    navigationBarTitleText: '积分兑换广场',
    navigationBarTextStyle: 'white',
  },
});
