export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/product/index',
    'pages/redeem/index',
    'pages/cart/index',
    'pages/address/index',
    'pages/profile/index',
    'pages/login/index',
    'pages/register/index',
    'pages/admin/index',
    'pages/admin/products',
    'pages/admin/codes',
    'pages/admin/users',
    'pages/admin/orders',
    'pages/admin/invites',
    'pages/admin/claims',
    'pages/admin/content',
    'pages/admin/categories',
    'pages/orders/index',
    'pages/order-detail/index',
    'pages/order-confirm/index',
    'pages/forgot-password/index',
    'pages/reset-password/index',
    'pages/claims/index',
    'pages/settings/index',
    'pages/content/index',
    'pages/content/detail',
    'pages/content/upload',
  ],
  window: {
    backgroundTextStyle: 'dark',
    navigationBarBackgroundColor: '#0a0b0f',
    navigationBarTitleText: '积分商城',
    navigationBarTextStyle: 'white',
  },
});
